### PR TITLE
default to verified SSL+ validate session

### PR DESCRIPTION
**Pull request by rlad78**
Attempts to address Issue #8 (SSL verification disabled)

`requests` [uses the host's CA store by default](https://docs.python-requests.org/en/latest/user/advanced/#ssl-cert-verification), no extra configuration is needed. However, in case of SSL failure, we can revert to `session.verify = False`.

Added an optional `__init__` argument `strict_ssl` which defaults to True. This causes any SSLError to be raised instead of handled by reverting back to unverified SSL. This may not be necessary, but the thought behind it is that if a user encounters an SSL issue, they can set this value to False to potentially solve the issue. The alternative would be to allow fallback to unverified SSL by default, which could potentially leave the user more vulnerable to MitM attacks. 

(I am not sure how likely these kinds of attacks would be, so if the `strict_ssl` arg is unnecessary, you can remove the "optional arg to require SSL" and "strict_ssl default to True" commits)

### CODE REVIEW

**Comment by rlad78** [comment]
Looks like the pytest task didn't supply a value for `cucm`. I think I probably don't have the permissions to use the env/secrets in actions. Or is it something else?

**Comment by bradh11** [comment]
As you suggested, it's failed tests because of an access issue to env variables (specifically for cucm host in this case).  Looking into how to resolve this

**Comment by bradh11** [comment]
i made a change to the PR to make strict_mode default setting be False by default to prevent breaking changes for people using the library and also allow people to use strict SSL verification if they choose.

**Comment by bradh11** [comment]
Here is the root cause of the issue for access to env variables:

image

As noted here, actions cannot access secrets from a forked repo.  Looking for a workaround...

**Comment by rlad78** [comment]
I've been looking into it too and haven't come up with much. I know that environments can require certain users to approve workflows on pull requests, though I don't know if that would change the restrictions that are imposed on a PR created from a forked repo. GitHub docs haven't been too helpful on that front.

image

**Pull request merged**
